/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [OrderProcessingSystem]    Script Date: 11/11/2017 8:52:38 PM ******/
CREATE DATABASE [OrderProcessingSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrderProcessingSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\OrderProcessingSystem.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrderProcessingSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\OrderProcessingSystem_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OrderProcessingSystem] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrderProcessingSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OrderProcessingSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OrderProcessingSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OrderProcessingSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OrderProcessingSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OrderProcessingSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [OrderProcessingSystem] SET  MULTI_USER 
GO

ALTER DATABASE [OrderProcessingSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OrderProcessingSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OrderProcessingSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OrderProcessingSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OrderProcessingSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OrderProcessingSystem] SET QUERY_STORE = OFF
GO

USE [OrderProcessingSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OrderProcessingSystem] SET  READ_WRITE 
GO

